apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
  labels:
    app: monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name: monitoring-app
        image: aj8399/my-flask-app:1.1
        ports:
        - containerPort: 5000 # Change the container port to 5000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 5000 # Ensure this port matches the containerPort
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000 # Ensure this port matches the containerPort
          initialDelaySeconds: 10
          periodSeconds: 10
